name: Store Auto Poster

on:
  schedule:
    - cron: '0 * * * *' # يشتغل تلقائياً كل ساعة
  workflow_dispatch: # زر التشغيل اليدوي

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Poster
        # هنا نضمن تشغيل الملف باسمه الصحيح
        run: python bot.py
